name: sa.nsr.zkteco_unlock
description: A new Flutter project.
version: 1.0.0
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.0
  webview_windows: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/resources/
    - assets/web/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/resources/icon.png"
